config/routes.rb
Rails.application.routes.draw do
  devise_for :couriers

  resources :waybills do 
    member do 
      put :accept
      put :reject
      put :yiqu
      put :submit_items
    end
    resources :items 
  end

  get 'home', to: 'home#index'

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/waybill.rb
class Waybill < ApplicationRecord
  belongs_to :order

  belongs_to :sender, polymorphic: true
  belongs_to :receiver, polymorphic: true

  belongs_to :from_address, class_name: Address
  belongs_to :to_address, class_name: Address

  include Workflow

  workflow_column :status 

  workflow do
    state :new do
      event :accept, transitions_to: :accepted
      event :reject, transitions_to: :rejected
    end
    state :accepted do
      event :finish, transitions_to: :finished
      event :reject, transitions_to: :reject
    end
    state :rejected
    state :finished
  end

  def accept
    self.order.next!
  end

  def finish
    self.order.next!
  end

  def reject
    self.order.prev!
  end
end

app/controllers/waybills_controller.rb
class WaybillsController < ApplicationController
  before_action :set_waybill, only: [:show, :edit, :update, :destroy, :accept, :reject, :yiqu, :submit_items]

  # GET /waybills
  # GET /waybills.json
  def index
    @pickup_waybills = current_courier.pickup_waybills
    @deliver_waybills = current_courier.deliver_waybills
  end

  # GET /waybills/1
  # GET /waybills/1.json
  def show
  end

  # GET /waybills/1/edit
  def edit
  end

  # DELETE /waybills/1
  # DELETE /waybills/1.json
  def destroy
    @waybill.destroy
    respond_to do |format|
      format.html { redirect_to waybills_url, notice: 'Waybill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def accept
    @waybill.accept!
    respond_to do |format|
      format.html { redirect_to :back, notice: '接单成功.' }
    end
  end

  def reject
    @waybill.reject!
    respond_to do |format|
      format.html { redirect_to :back, notice: '拒单成功.' }
    end
  end

  def yiqu
    respond_to do |format|
      if @waybill.yiqu
        format.html { redirect_to :back, notice: '取件成功.' }
      else
        format.html { redirect_to :back, alert: "取件失败. #{@waybill.errors}" }
      end
    end
  end

  def submit_items
    respond_to do |format|
      @waybill.order.generate_voucher
      format.html { redirect_to :back, notice: '计价信息提交成功.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waybill
      @waybill = Waybill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waybill_params
      params.fetch(:waybill, {})
    end
  end

app/helpers/waybill_helper.rb
module WaybillHelper
  def show_waybill_status(status)
    case status
    when 'new'
      '初始'
    when 'accepted'
      '已接单'
    when 'rejected'
      '已拒单'
    end
  end
end

app/helpers/waybills_helper.rb
module WaybillsHelper
end

app/views/waybills/_form.html.slim
= simple_form_for(@waybill) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/waybills/edit.html.slim
h1 Editing waybill

== render 'form'

= link_to 'Show', @waybill
'|
= link_to 'Back', waybills_path

app/views/waybills/index.html.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading#operations
        | 取件单
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 从
              th width='15%' 到
              th width='15%' 状态
              th width='15%' 期望执行
              th width='15%' 实际执行
              th
          tbody
            - @pickup_waybills.each do |waybill|
              tr
                td
                  = waybill.from_address
                td
                  = waybill.to_address
                td
                  = show_waybill_status waybill.status
                td
                  = date_time waybill.exp_time
                td
                  = date_time waybill.actual_time
                td = link_to 'Show', waybill

.row
  .col-md-12
    .panel.panel-default
      .panel-heading#operations
        | 送件单
      .panel-body
        table.table.table-striped
          thead
            tr
              th width='15%' 联系人
              th width='15%' 地址
              th width='15%' 状态
              th width='15%' 期望执行
              th width='15%' 实际执行
              th
          tbody
            - @deliver_waybills.each do |waybill|
              tr
                td
                  - if waybill.receiver_type == 'User' 
                    = waybill.order.address
                  - else
                    = waybill.receiver.address
                td
                  - if waybill.receiver_type == 'User' 
                    = waybill.order.address
                  - else
                    = waybill.receiver.address
                td
                  = show_waybill_status waybill.status
                td
                  = date_time waybill.exp_time
                td
                  = date_time waybill.actual_time
                td = link_to 'Show', waybill

app/views/waybills/new.html.slim
h1 New waybill

== render 'form'

= link_to 'Back', waybills_path

app/views/waybills/show.html.slim
ol.breadcrumb
  li.active 
    = link_to '取送单', waybills_path

.clear
br

.row
  .col-md-12
    .panel.panel-default
      .panel-heading#operations
        | 基本信息
      .panel-body
        table.table.table-striped
          tr
            td width='13%' 取件地址
            td width='20%' = @waybill.from_address
            td width='13%' 送地址
            td width='20%' = @waybill.to_address
          tr
            td width='13%' 当前状态
            td width='20%' = show_waybill_status @waybill.status
            td width='13%' 期望执行
            td width='20%' = date_time @waybill.exp_time
            td width='13%' 实际执行
            td width='20%' = date_time @waybill.actual_time
          - voucher = @waybill.order.voucher
          tr
            td width='13%' 订单金额
            td width='20%' 
              = @waybill.order.voucher.money if voucher
            td width='13%' 支付状态
            td width='20%' 
              = @waybill.order.voucher.status ? '待支付' : '已支付' if voucher
  - if @waybill.new?
    = link_to '接单', accept_waybill_path(@waybill), method: :put, class: 'btn btn-info btn-sm'
    = link_to '拒单', reject_waybill_path(@waybill), method: :put, class: 'btn btn-info btn-sm'
  - elsif @waybill.accepted?
    = link_to '已取', yiqu_waybill_path(@waybill), method: :put, class: 'btn btn-info btn-sm'
  

.clear
br

.row
  .col-md-12
    .panel.panel-default
      .panel-heading#operations
        | 分拣信息
      .panel-body
        table.table.table-striped
          tr
            th 产品
            th 数量
            th 单价
            th 总价
            th
            th
          - @waybill.order.items.each do |item|
            tr
              td = item.product
              td = item.amount
              td = item.price
              td = item.amount * item.price
              td = link_to 'Edit', edit_waybill_item_path(@waybill, item)
              td = link_to 'Destroy', waybill_item_path(@waybill, item), data: { confirm: 'Are you sure?' }, method: :delete
      - unless @waybill.order.voucher
        .panel-footer
          = link_to '分拣', new_waybill_item_path(@waybill), class: 'btn btn-info btn-sm'
          |    
          = link_to '计价完毕', submit_items_waybill_path(@waybill), class: 'btn btn-info btn-sm', method: :put